### ISSUE TITLE
[Repository] Introduce pre-commit (git hooks automation)

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#26]
### Suggestion

A repository can easily be messed up with specific settings in the various ide's. 
This gets really messy when reviewing stuff and takes away the precious time we all have.

[pre-commit](https://pre-commit.com/) is a framework for managing git hooks. They have all kinds of stuff already available. The things we are interested about are specified in our editorconfig. However if you run an ide which doesn't have editorconfig installed, you run into issues. This is where `pre-commit` comes in handy as it'lll block your commit until you fixed these things we list.

### Use case

Preventing faulty / messy commits which are easy fixable and identifiable by automation tools.

### Extra info/examples/attachments

* https://pre-commit.com/
* https://github.com/pre-commit/pre-commit
* https://github.com/pre-commit/pre-commit-hooks

### Todo
- [x] Add pre-commit to the project
- [x] Add pre-commit-hooks to the project (configuration file)
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-case-conflict
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-executables-have-shebangs
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-shebang-scripts-are-executable
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-json
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-merge-conflict
    - [x] https://github.com/pre-commit/pre-commit-hooks#check-yaml
    - [x] https://github.com/pre-commit/pre-commit-hooks#fix-byte-order-marker
    - [x] https://github.com/pre-commit/pre-commit-hooks#end-of-file-fixer
    - [x] https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending
    - [x] https://github.com/pre-commit/pre-commit-hooks#pretty-format-json
    - [x] https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace
- [x] Fix current issues

*note*
If you have a pre-commit hook you'd want to add please contribute to the above project <3
