### ISSUE TITLE
[Spec] List the Metadata tags

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#7]
As the format has been out there for quite some time a lot of tags have been used.
Let's try to come up with a definitive list of all the Metadata tags (artist, title, etc)  out there
This way we can go through them one by one and eventually attach them to a versioning strategy.

### To help...
@rakuri255 already created a great overview of tags and note types. Linked repository: https://github.com/rakuri255/Ultrastar_txt_documentation

### Todo
* [x] List all the Metadata tags
* [x] Describe the function of the tag
* [ ] Optional: Describe where the tag came from.

### Out of scope
* Adding a version to each tag

**Comment by Baklap4** [comment]
@bohning and @rakuri255 did a great inventarisation already. I'm currently wondering how to add this to the repository in a way that's easy to maintain and build upon

For now here's a little screencap:
![image](https://github.com/UltraStar-Deluxe/format/assets/3918517/fc704809-0d77-45f3-9162-f1649cd450b0)

**Comment by rakuri255** [comment]
@Baklap4 World Party `#P2` is unsupported 😃

**Comment by rakuri255** [comment]
You can publish this list in google, so we all can see it and edit it.

**Comment by bohning** [comment]
https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit?usp=drivesdk

**Comment by rakuri255** [comment]
I changed the `#P2` for WorldParty in the google sheet

**Comment by marwin89** [comment]
This task seems to be done ✅ 🎈 
please re-open if needed.
