### ISSUE TITLE
[Spec] List the NoteTypes

### ISSUE THREAD

**Issue by Baklap4** [UltraStar-Deluxe/format#8]
As the format has been out there for quite some time we've kinda settled on some NoteTypes to use.
Let's try to come up with a definitive list of all the NoteTypes (Normal, Golden, Rap, Freestyle, Break, etc) out there
This way we can go through them one by one and eventually attach them to a versioning strategy.

### To help...
@rakuri255 already created a great overview of tags and note types. Linked repository: https://github.com/rakuri255/Ultrastar_txt_documentation

### Todo
* [x] List all the NoteTypes 
* [x] Describe the function of the NoteType
* [ ] Optional: Describe where the NoteType came from.

### Out of scope
* Adding a version to each NoteType

**Comment by Baklap4** [comment]
@bohning and @rakuri255 did a great inventarisation already. I'm currently wondering how to add this to the repository in a way that's easy to maintain and build upon

For now here's a little screencap:
![image](https://github.com/UltraStar-Deluxe/format/assets/3918517/1c015224-d090-4389-ab94-9866f9c08c2b)

**Comment by rakuri255** [comment]
Should you include the software version number of the product? The games could all get an update and support something new. Or someone wants to use an old version.

**Comment by Baklap4** [comment]
That'd make for a 3d spreadsheet.. would be nice, but is harder to project to the enduser in an easy overview on our website
Any idea to tackle that @rakuri255 ?

I do like the idea to include the software version as it shows exactly what is and what is not supported which is a great piece of info

**Comment by rakuri255** [comment]
@marwin89  We should keep it as simple as possible and show a maximum of 2 versions. 
I would say we version only the status change. 
If V1.0 is red and the newer versions are still red, then we just leave V1.0 or update to the new version by demand. But do not show the old versions. It is to be expected that the old versions are also red. Or write <V3.0. 

If V4.0 changes to green, then we show the latest version which has been red and then update on demand always the green one. It is to be expected with green that all new versions continue to function. e.g. <V3.0 red and >V4.0 green.

So you save the update effort.

**Comment by rakuri255** [comment]
@marwin89 We need also a comment section for special cases. e.g. Vocaluxe supports Rap notes but only displays it as freestyle.

**Comment by marwin89** [comment]
> @marwin89 We need also a comment section for special cases. e.g. Vocaluxe supports Rap notes but only displays it as freestyle.

definitely - we need a comment section, I'm thinking about how to best display tables in on the website (incl. mobile view). Tables don't respond to the width if there are many columns. oh but now I see there seems to be a class in bootstrap 3... for responsive tables..

**Comment by marwin89** [comment]
@rakuri255 , we just talked in discord with nianna and asgard about versions.
We agreed together on: the easiest solution is to **write the lowest version that supports a particular tag** like 

`>=v.3.1.0`

**Comment by Baklap4** [comment]
Through the help of git we can identify the lowest version if support for a tag is deleted/deprecated it needs to be mentioned in maybe a comment section @rakuri255 already mentioned :)

**Comment by rakuri255** [comment]
Sure. Sounds good!

**Comment by marwin89** [comment]
According to the [meta-tag & note-tag spreadsheet](https://docs.google.com/spreadsheets/d/13fj_wtRHbSjaOaS1ehmCogoeFV9MyqY1eeiqkrJfhDA/edit#gid=135693021)


This task seems to be done ✅ 🎈 
please re-open if needed.
